"""db

Revision ID: 6e768acb00fe
Revises: 
Create Date: 2019-06-12 14:53:08.886581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e768acb00fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset_columns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_name', sa.String(length=128), nullable=True),
    sa.Column('column_name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('task',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_name'), 'task', ['name'], unique=False)
    op.create_table('user_dataset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('dataset', sa.String(length=140), nullable=True),
    sa.Column('dataset_name', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset')
    )
    op.create_index(op.f('ix_user_dataset_timestamp'), 'user_dataset', ['timestamp'], unique=False)
    op.create_table('data_subset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('dataset_name', sa.String(length=128), nullable=True),
    sa.Column('subset', sa.String(length=140), nullable=True),
    sa.Column('subset_name', sa.String(length=128), nullable=True),
    sa.Column('columns_subset', sa.String(length=256), nullable=True),
    sa.Column('target_column', sa.String(length=140), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['user_dataset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subset_id', sa.Integer(), nullable=True),
    sa.Column('subset_name', sa.String(length=128), nullable=True),
    sa.Column('analysis', sa.String(length=128), nullable=True),
    sa.Column('analysis_name', sa.String(length=128), nullable=True),
    sa.Column('analysis_score', sa.Float(), nullable=True),
    sa.Column('analysis_model', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['subset_id'], ['data_subset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analysis_result')
    op.drop_table('data_subset')
    op.drop_index(op.f('ix_user_dataset_timestamp'), table_name='user_dataset')
    op.drop_table('user_dataset')
    op.drop_index(op.f('ix_task_name'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('dataset_columns')
    # ### end Alembic commands ###
